dependencies:
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.42
- alias: prow
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.1009
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 2.0.942
